export const createTableClientes = `CREATE TABLE clientes (
    id INTEGER NOT NULL AUTOINCREMENT,
    id_dependente INTEGER,
    aplicativo TEXT,
    situacao TEXT,
    PRIMARY KEY(id),
    FOREIGN KEY(id_dependente) REFERENCES clientes_dependentes(id)
)`;

export const createTablePlanosFunerarios = `CREATE TABLE planos_funerarios (
    id INTEGER NOT NULL AUTOINCREMENT,
    cliente TEXT,
    indicacao TEXT,
    tecnico TEXT,
    profissional TEXT,
    taxa_adesao NUMERIC,
    valor_bruto NUMERIC,
    data_inicial DATE,
    forma_pagamento TEXT,
    condicao_pagamento TEXT,
    qtd_parcelas TEXT,
    indicacao_parcelas TEXT,
    tipo_liberacao TEXT,
    carencia TEXT,
    carencia_vencimento DATE,
    rg_r_pedente TEXT,
    cpf_r_pendente TEXT,
    residencia_r_pendente TEXT,
    casamento_r_pendente TEXT,
    data_os DATE,
    data_carne DATE,
    data_entrega DATE,
    hora_realizacao TEXT,
    obs TEXT,
    obs_internas TEXT,
    contas_lancadas TEXT,
    contas_pagar INTEGER,
    situacao TEXT,
    criado_por INTEGER,
    atualizado_por INTEGER,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    repetir_valor TEXT,
)`;

export const createTablePlanosFunerariosDependentes = `CREATE TABLE planos_funerarios_dependentes (
    id INTEGER NOT NULL AUTOINCREMENT,
    plano_id INTEGER,
    nome TEXT,
    tipo TEXT,
    telefone TEXT,
    rg TEXT,
    cpf TEXT,
    data_nasc DATE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    dependente_id INTEGER
)`

export const createTablePlanosFunerariosParcelas = `CREATE TABLE planos_funerarios_parcelas (
    id INTEGER NOT NULL AUTOINCREMENT,
    plano_id INTEGER,
    parcela_numero INTEGER,
    parcela_data DATE,
    parcela_valor NUMERIC,
    parcela_forma_pagamento INTEGER,
    parcela_pago INTEGER,
    parcela_obs TEXT,
    created_at TIMESTAMP,
    created_at TIMESTAMP,
)`

export const createTablePlanosFunerariosServicos = `CREATE TABLE planos_funerarios_service(
    id INTEGER NOT NULL AUTOINCREMENT,
    plano_id INTEGER,
    servico_plano INTEGER,
    servico_id INTEGER,
    servico_quantidade INTEGER,
    servico_parcelas INTEGER,
    servico_valor_unitario NUMERIC,
    servico_valor_total NUMERIC,
    created_at TIMESTAMP,
    update_at TIMESTAMP,
)`

export const planosFunerariosStatus = `CREATE TABLE planos_funerarios_status(
    id INTEGER NOT NULL AUTOINCREMENT,
    plano_id INTEGER,
    data DATE,
    obs TEXT,
    situacao TEXT,
    created_at TIMESTAMP,
    update_at TIMESTAMP,
)`

export const contasReceber = `CREATE TABLE contas_receber(
    id INTEGER NOT NULL AUTOINCREMENT,
    descricao TEXT,
    conta_bancaria INTEGER,
    categoria INTEGER,
    cliente INTEGER,
    vendedor INTEGER,
    atendente_l_comissao NUMERIC,
    vendedor_2 INTEGER,
    atendente_2_comissao NUMERIC,
    vencimento DATE,
    data_liquidacao DATE,
    valor_liquidacao NUMERIC,
    valor NUMERIC,
    tipo_registro TEXT,
    data_emissao DATE,
    pago INTEGER,
    parcial INTEGER,
    situacao INTEGER,
    status TEXT,
    taxa_paga INTEGER,
    protestar INTEGER,
    n_doc TEXT,
    forma_pagamento INTEGER,
    centro_custos INTEGER,
    ocorrencia TEXT,
    obs TEXT,
    referencia TEXT,
    n_os INTEGER,
    n_parcelas INTEGER,
    n_carne INTEGER,
    n_carne_boleto INTEGER, 
    urlcarne TEXT,
    urlboleto TEXT,
    n_boleto INTEGER,
    email_enviado INTEGER,
    criado_por INTEGER,
    atualizado_por INTEGER,
    created_at TIMESTAMP,
    update_at TIMESTAMP,
)`