export const createTableClientes = `CREATE TABLE clientes (
    id INTEGER NOT NULL AUTOINCREMENT,
    id_dependente INTEGER,
    aplicativo TEXT,
    situacao TEXT,
    pessoa TEXT,
    cnpjcpf TEXT,
    rg TEXT,
    emissor TEXT,
    raxao_social TEXT,
    nome_fantasia TEXT,
    data_nascimento DATE,
    idade TEXT,
    naturalidade TEXT,
    sexo TEXT,
    estado_civil TEXT,
    nome_pai TEXT,
    nome_mae TEXT,
    inscricao_municipal TEXT,
    inscricao_mestadual TEXT,
    cep TEXT,
    endereco TEXT,
    numero TEXT,
    complemento TEXT,
    bairro TEXT,
    cidade TEXT,
    ibge TEXT,
    estado TEXT,
    celular TEXT,
    email TEXT,
    obs TEXT,
    tipo_cadastral TEXT,
    local_obito TEXT,
    motivo_obito TEXT,
    data_obito DATE,
    data_atestado DATE,
    profissao TEXT,
    cep_obito TEXT,
    endereco_obito TEXT,
    numero_obito TEXT,
    complemento_obito TEXT,
    bairro_obito TEXT,
    cidade_obito TEXT,
    estado_obito TEXT,
    categoria INTEGER,
    cNome TEXT,
    cTelefone TEXT,
    cRamal TEXT,
    cFax TEXT,
    cCelular TEXT,
    cEmail TEXT,
    cWebsite TEXT,
    eTipo_endereco TEXT,
    eTipo_pessoa TEXT,
    eCnpjcpf TEXT,
    eCep TEXT,
    eEndereco TEXT,
    eBairro TEXT,
    eNumero TEXT,
    eComplemento TEXT,
    eCidade TEXT,
    eEstado TEXT,
    lista_preco INTEGER,
    condicao_pagamento INTEGER,
    conta_bancaria INTEGER,
    limite_credito NUMERIC,
    limite_ultrapassar INTEGER,
    data_inicial DATE,
    data_final DATE,
    created_at DATE,
    updated_at DATE,
    data_cadastro DATE,
    hora_cadastro TEXT,
    horario TEXT,
    plano TEXT,
    taxa_adesao TEXT,
    dia_parcela TEXT,
    deve_receber_sms TEXT NOT NULL DEFAULT "S",
    deve_receber_torpedo_voz TEXT NOT NULL DEFAULT "S",
    criado_por INTEGER,
    atualizado_por INTEGER,
    religiao TEXT,
    indicacao INTEGER,
    PRIMARY KEY(id),
    FOREIGN KEY(id_dependente) REFERENCES clientes_dependentes(id)
)`;

export const createTableClientesDependentes = `CREATE TABLE clientes_dependentes (
    id INTEGER NOT NULL AUTOINCREMENT,
    cliente INTEGER,
    cliente_id INTEGER,
    id_dependente INTEGER,
    numero INTEGER,
    nome TEXT,
    tipo TEXT,
    telefone TEXT,
    rg TEXT,
    cpf TEXT,
    data_nasc DATE,
    created_at DATE,
    updated_at DATE,
    criado_por INTEGER,
    PRIMARY KEY(id),
    FOREIGN KEY(cliente_id) REFERENCES clientes(id)
)`;

export const createTableContasReceberBaixas = `CREATE TABLE contas_receber_baixas (
    id INTEGER NOT NULL AUTOINCREMENT,
    conta_id INTEGER,
    referencia TEXT,
    data_liquidacao DATE,
    valor NUMERIC,
    juros NUMERIC,
    desconto NUMERIC,
    acrescimo NUMERIC,
    conta_bancaria INTEGER,
    forma_pagamento INTEGER,
    tipo_pagamento TEXT,
    created_at DATE,
    updated_at DATE,
    baixa_por INTEGER,
    PRIMARY KEY(id),
    FOREIGN KEY(conta_id) REFERENCES contas_receber(id)
)`;

export const createTableContasReceberParcelas = `CREATE TABLE contas_receber_parcelas (
    id INTEGER NOT NULL AUTOINCREMENT,
    conta_receber_id INTEGER,
    parcela_numero INTEGER,
    parcela_data DATE,
    parcela_valor NUMERIC,
    parcela_forma_pagamento INTEGER,
    parcela_obs TEXT,
    created_at DATE,
    updated_at DATE,
    PRIMARY KEY(id),
    FOREIGN KEY(conta_receber_id) REFERENCES contas_receber(id)
)`;

export const createTablePlanosFunerarios = `CREATE TABLE planos_funerarios ()`;
