export class ClienteModel {
  id?: number;
  responsavel?: string;
  situacao?: string;
  categoria?: string;
  pessoa?: string;
  cnpjcpf?: string;
  cnpj?: string;
  cpf?: string;
  rg?: string;
  emissor?: string;
  naturalidade?: string;
  nome_fantasia?: string;
  razao_social?: string;
  data_nascimento?: any;
  idade?: string | number;
  sexo?: string;
  estado_civil?: string;
  nome_pai?: string;
  nome_mae?: string;
  inscricao_municipal?: string;
  inscricao_estadual?: string;
  cep?: string;
  endereco?: string;
  numero?: string;
  complemento?: string;
  bairro?: string;
  cidade?: string;
  ibge?: string;
  estado?: string;
  telefone?: string;
  celular?: string;
  whatsapp?: string;
  email?: string;
  obs?: string;
  tipo_cadastro?: string;
  local_obito?: string;
  motivo_obito?: string;
  data_obito?: any;
  data_atestado?: any;
  profissao?: any;
  cep_obito?: any;
  endereco_obito?: string;
  numero_obito?: string;
  complemento_obito?: string;
  bairro_obito?: string;
  cidade_obito?: string;
  estado_obito?: any;
  cNome?: string;
  cNascimento?: string;
  cTelefone?: string;
  cRamal?: string;
  cFax?: string;
  cCelular?: string;
  cEmail?: string;
  cWebsite?: string;
  eTipo_endereco?: string;
  eTipo_pessoa?: string;
  eCnpjcpf?: string;
  eCnpj?: string;
  eCpf?: string;
  eCep?: string;
  eEndereco?: string;
  eBairro?: string;
  eNumero?: string;
  eComplemento?: string;
  eCidade?: string;
  eEstado?: string;
  lista_preco?: any;
  condicao_pagamento?: any;
  limite_credito?: any;
  limite_ultrapassar?: any;
  conta_bancaria?: any;
  data_inicial?: any;
  data_final?: any;
  data_cadastro?: any;
  hora_cadastro?: any;
  dependentes?: IDependentes[];
  pesquisados?: IDependentes[];
  subDependentes?: IDependentes[];
  deve_receber_sms?: string;
  deve_receber_torpedo_voz?: string;
  criado_por: any;
  atualizado_por: any;
  religiao?: string;
  indicacao?: string;
  indicacao_nome?: string;

  /**
   * Constructor
   *
   * @param data
   *     */
  constructor(data?) {
    data = data || {};
    this.id = data.id || '';
    this.responsavel = this.responsavel  || '';
    this.situacao = this.situacao || 'Ativo';
    this.categoria = this.categoria || '';
    this.pessoa = this.pessoa || 'PF';
    this.cnpjcpf = this.cnpjcpf || '';
    this.cnpj = this.cnpj || '';
    this.cpf = this.cpf || '';
    this.rg = this.rg || '';
    this.emissor = this.emissor || '';
    this.naturalidade = this.naturalidade || '';
    this.nome_fantasia = this.nome_fantasia || '';
    this.razao_social = this.razao_social || '';
    this.data_nascimento = this.data_nascimento || '';
    this.idade = this.idade || '';
    this.sexo = this.sexo || 'Masculino';
    this.estado_civil = this.estado_civil || 'Solteiro(a)';
    this.nome_pai = this.nome_pai || '';
    this.nome_mae = this.nome_mae || '';
    this.inscricao_municipal = this.inscricao_municipal || '';
    this.inscricao_estadual = this.inscricao_estadual || '';
    this.cep = this.cep || '';
    this.endereco = this.endereco || '';
    this.numero = this.numero || '';
    this.complemento = this.complemento || '';
    this.bairro = this.bairro || '';
    this.cidade = this.cidade || '';
    this.ibge = this.ibge || '';
    this.estado = this.estado || '';
    this.telefone = this.telefone || '';
    this.celular = this.celular || '';
    this.whatsapp = this.whatsapp || '';
    this.email = this.email || '';
    this.obs = this.obs || '';
    this.tipo_cadastro = this.tipo_cadastro || 'Cliente';
    this.local_obito = this.local_obito || '';
    this.motivo_obito = this.motivo_obito || '';
    this.data_obito = this.data_obito || '';
    this.data_atestado = this.data_atestado || '';
    this.profissao = this.profissao || '';
    this.cep_obito = this.cep_obito || '';
    this.endereco_obito = this.endereco_obito || '';
    this.numero_obito = this.numero_obito || '';
    this.complemento_obito = this.complemento_obito || '';
    this.bairro_obito = this.bairro_obito || '';
    this.cidade_obito = this.cidade_obito || '';
    this.estado_obito =  this.estado_obito || '';
    this.cNome = this.cNome || '';
    this.cNascimento = this.cNascimento || '';
    this.cTelefone = this.cTelefone || '';
    this.cRamal = this.cRamal || '';
    this.cFax = this.cFax || '';
    this.cCelular = this.cCelular || '';
    this.cEmail = this.cEmail || '';
    this.cWebsite = this.cWebsite || '';
    this.eTipo_endereco = this.eTipo_endereco || '';
    this.eTipo_pessoa = this.eTipo_pessoa || '';
    this.eCnpjcpf = this.eCnpjcpf || '';
    this.eCnpj = this.eCnpj || '';
    this.eCpf = this.eCpf || '';
    this.eCep = this.eCep || '';
    this.eEndereco = this.eEndereco || '';
    this.eBairro = this.eBairro || '';
    this.eNumero = this.eNumero || '';
    this.eComplemento = this.eComplemento || '';
    this.eCidade = this.eCidade || '';
    this.eEstado = this.eEstado || '';
    this.lista_preco = this.lista_preco || '';
    this.condicao_pagamento = this.condicao_pagamento || '';
    this.limite_credito = this.limite_credito || '';
    this.limite_ultrapassar = this.limite_ultrapassar || '';
    this.conta_bancaria = this.conta_bancaria || '';
    this.data_inicial = this.data_inicial || '';
    this.data_final = this.data_final || '';
    this.data_cadastro = this.data_cadastro || '';
    this.hora_cadastro = this.hora_cadastro || '';
    this.dependentes = this.dependentes || [];
    this.pesquisados = [];
    this.subDependentes = this.subDependentes || [];
    this.deve_receber_sms = this.deve_receber_sms || 'Sim';
    this.deve_receber_torpedo_voz = this.deve_receber_torpedo_voz || 'Sim';
    this.criado_por = this.criado_por || '';
    this.atualizado_por = this.atualizado_por || '';
    this.religiao = this.religiao || '';
    this.indicacao = this.indicacao || '';
    this.indicacao_nome = this.indicacao_nome || '';
  }
}

export interface IEnderecos {
  tipoDeEndereco?: string;
  tipoDePessoa?: string;
  cpf?: number;
  endereco?: number;
  numero?: number;
  complemento?: string;
  bairro?: string;
  cidade?: string;
  estado?: string;
  religiao?: string;
}

export interface IDadosAdicionais {
  categoriaClassificacao?: string;
  situacao?: string;
}

export interface IDependentes {
  numero?: number;
  id?: number;
  cliente?: number;
  cliente_id?: number;
  nome?: string;
  tipo?: string;
  telefone?: string;
  rg?: string;
  cpf?: string;
  data_nasc?: Date | null;
  criado_por?: number;
  pesquisados?: any[];
  created_at?: Date;
  updated_at?: Date;
}
